---
title: 'R for Transport Applications: summary'
output:
  word_document: default
  pdf_document: default
  html_document: default
---

## Topic Area (and proposed title if known)

Topic area: data analysis and programming

Title: R for Transport Applications: Handling Big Data in Spatial World

## Course content (brief description and balance of lecture/practical sessions)

### Day 1: Intermediate R and the basics of R as a GIS

- Registration and refreshments (9:00 - 9:30)

- An introduction to R, RStudio and the power of packages (9:30 - 10:30)
    - Why R for transport data?
    - Boosting productivity with RStudio, space-aged IDE
    - How R's ecosystem works: packages, tutorials, help forums and code sharing sites

- Objects, functions and concepts for efficient R programming (10:30 - 11:30) 
    - 15 minutes intro, 45 minutes hands on
    - An introduction to classes
    - Types of vector data
    - Dimensionality: lists, matrices, data frames and arrays

- Data manipulation (11:30 - 12:30)
    - Subestting vectors (one dimensional datasets)
    - Regex for selecting and replacing text strings
    - A taster of plotting methods

**LUNCH: 12:30 - 13:30**

- Data carpentry with **dplyr** (13:30 - 15:30)
    - Subsetting rows and columns
    - Creating new variables
    - Grouping and aggregating
    - Joining tables together

**15:30 - 15:45 Refreshments**

- Spatial data in R: classes and projections (15:45 - 16:00)
    - SpatialPoints
    - SpatialPointsDataFrame
    - Using `spTransform()`

- Data visualisation (16:00 - 16:30)
    - Using R's base graphics for data exploration ()
    - Getting your head around **ggplot2**

### Day 2: R for transport applications

- Registration and refreshments (9:00 - 9:30)

- Recap on R as a GIS: a worked example (9:30 - 10:00) 
    - Live demo of the Propensity to Cycle Tool
    - Practical walk through illustrating a transport planning workflow in R

- Spatial operations for transport research (10:00 - 11:00)
    - Subsetting data
    - Spatial aggregation
    - Buffers, unions and binds
    
- Transport data with **stplanr** (11:00 - 12:30)
    - Handling OD data
    - Creating 'desire lines' from OD and zone data
    - Route allocation and route network creation

**LUNCH: 12:30 - 13:30**

- Traffic data and pollution analysis with R (13:30 - 15:30, delivered by [Dr James Tate](http://www.its.leeds.ac.uk/people/j.tate)) 
    - An introduction to the **openair** package
    - Traffic count data
    - Meteorological data
    - Air pollution data: daily, weekly and seasonal variability
    - Visualising air pollution data and next steps

**15:30 - 15:45 Refreshments**

- Advanced graphics for transport applications: an illustration using **tmap**
- Taking it further, adding interactivity and applying the methods to your data (16:00 onwards)


## Link to current or proposed postgraduate teaching activity

This links to the introductory computing 1 off session and the R practicals in the SSPA module.

## Link to research activities/impact

Links to the propensity to cycle tool (PCT) and engagement with Local Authorities and the private sector.


## Primary potential market 

Public sector and consultancy analysts


## Timeframe before first delivery (within 6 months, 12 months, etc.)

Within 6 months.

**Dates:** 26^th^ and 27^th^ April

## Delivery method

2 days in LIDA, Leeds, full days.
